# Generated by Django 5.0.2 on 2024-03-05 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('level', models.IntegerField()),
                ('cp_count', models.IntegerField()),
                ('sync', models.CharField(choices=[('اکتیوژن', 'Activsion'), ('فیسبوک', 'Facebook'), ('گوگل', 'Google'), ('لاین', 'Line')], max_length=100)),
                ('region', models.CharField(choices=[('هند 220 CP', 'India'), ('ایران 360 CP', 'Iran'), ('اروپا 560 CP', 'Europe'), ('CP 560 آمریکا', 'America')], max_length=100)),
                ('image_lobby', models.ImageField(upload_to='Ads/<django.db.models.fields.CharField>')),
                ('image_guns', models.ImageField(upload_to='Ads/<django.db.models.fields.CharField>')),
                ('image_character', models.ImageField(upload_to='Ads/<django.db.models.fields.CharField>')),
                ('image_danes', models.ImageField(upload_to='Ads/<django.db.models.fields.CharField>')),
                ('image_optional', models.ImageField(upload_to='Ads/<django.db.models.fields.CharField>')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ads', to='ads.filter')),
            ],
        ),
    ]
