# Generated by Django 5.0.2 on 2024-03-05 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image_character',
            field=models.ImageField(upload_to='Ads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image_danes',
            field=models.ImageField(upload_to='Ads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image_guns',
            field=models.ImageField(upload_to='Ads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image_lobby',
            field=models.ImageField(upload_to='Ads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image_optional',
            field=models.ImageField(upload_to='Ads/%Y/%m/%d/'),
        ),
    ]
