# Generated by Django 5.0.2 on 2024-03-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ads_user_alter_ads_image_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='battle_pass',
            field=models.TextField(blank=True, null=True),
        ),
    ]
