# Generated by Django 5.0.2 on 2024-03-21 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ads_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='available',
            new_name='verification',
        ),
    ]
