# Generated by Django 5.0.2 on 2024-03-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_rename_available_ads_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
