# Generated by Django 5.0.2 on 2024-03-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_remove_ads_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image_optional',
            field=models.ImageField(blank=True, null=True, upload_to='Ads/%Y/%m/%d/'),
        ),
    ]
