# Generated by Django 5.0.2 on 2024-03-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_ads_image_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='slug',
        ),
    ]
