# Generated by Django 5.0.2 on 2024-03-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_remove_ads_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='region',
            field=models.CharField(choices=[('iran', 'ایران 360 CP'), ('india', 'هند 220 CP'), ('europe', 'اروپا 560 CP'), ('america', 'CP 560 آمریکا')], max_length=100),
        ),
    ]
