# Generated by Django 5.0.2 on 2024-03-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_alter_ads_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='sync',
            field=models.CharField(choices=[('ACTIVSION', 'اکتیوژن'), ('FACEBOOK', 'فیسبوک'), ('GOOGLE', 'گوگل'), ('LINE', 'لاین')], max_length=100),
        ),
    ]
