# Generated by Django 5.0.2 on 2024-03-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
